apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-scripts
data:
  library.sh: |-
    #! /bin/sh 

     zp=2181
     zk=zookeeper
    bin=/opt/kafka/bin
    zks="zk-0.zk:$zp,zk-1.zk:$zp,zk-2.zk:$zp"

  run.sh: |-
    #! /bin/sh

    . $(dirname $0)/library.sh

    cfg=/tmp/server.properties
    cmd=$bin/kafka-server-start.sh
    bsc=/opt/kafka/config/base-$(basename $cfg)

    echo "Generate config $cfg based from $bsc"
    cp -rfv $bsc $cfg

    echo "Generate extra config settings"
    {   
        echo "broker.id=${HOSTNAME##*-}"
        echo "log.dirs=/var/lib/kafka/data"
        echo "logging.level=INFO"
        echo "num.network.threads=8"
        echo "num.io.threads=16"
        echo "num.partitions=3"
        echo "num.replica.fetchers=3"
        echo "num.recovery.threads.per.data.dir=1"
        echo "delete.topic.enable=true"
        echo "auto.create.topics.enable=false"
        echo "default.replication.factor=3"
        echo "$zk.connect=$zks/kafka"
        echo "$zk.set.acl=false"
    } > $cfg

    exec $cmd $cfg

  health-check.sh: |-
    #! /bin/sh 

    . $(dirname $0)/library.sh

    $bin/kafka-topics.sh --$zk $zks --list

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: init
        image: alpine:3.12
        command:
        - sh
        - -c
        - mkdir -pv /k/data; chown -v 500. /k/data
        volumeMounts:
        - name: data
          mountPath: /k
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: statemood/kafka:2.5.0
        command:
        - sh
        - -c
        - /opt/bin/run.sh
        resources:
          requests:
            memory: 8Gi
            cpu: "2"
          limits:
            memory: 8Gi
            cpu: "2"
        ports:
        - containerPort: 9092
          name: server
        env:
        - name: KAFKA_HEAP_OPTS
          value : "-Xmx4g -Xms4g"
        livenessProbe:
          exec:
            command:
            - /opt/bin/health-check.sh
          initialDelaySeconds: 45
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - /opt/bin/health-check.sh
          initialDelaySeconds: 45
          timeoutSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka
        - name: scripts
          mountPath: /opt/bin
        - name: base-config
          mountPath: /opt/kafka/config/base-server.properties
          subPath: base-server.properties
      volumes:
      - name: kbc
        configMap:
          defaultMode: 0444
          name: kafka-base-config
      - name: scripts
        configMap:
          defaultMode: 0755
          name: kafka-scripts
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: data
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Gi